### PR TITLE
Use a Ledger instead of a bare UTXOSet

### LINKED ISSUE #150: Faucet should use Ledger from Agora
Maybe Faucet should just have a Ledger ?

_Originally posted by @Geod24 in https://github.com/bosagora/faucet/issues/145#issuecomment-981172416_

### PR DESCRIPTION
**Pull request by Geod24**
E_NEEDSTESTING

Fixes #150

### CODE REVIEW

**Comment by Geod24** [comment]
So far found https://github.com/bosagora/infrastructure/issues/220 and https://github.com/bosagora/agora/pull/2881 and there seems to be another one, at least.
Pre-requisite : #165 .

**Comment by Geod24** [comment]
Latest issue:
```
2022-01-19 14:34:23,281 Info [agora.consensus.state.Ledger] - Completed externalization of block #19
2022-01-19 14:34:23,305 Info [agora.consensus.state.Ledger] - Beginning externalization of block #20
2022-01-19 14:34:23,305 Info [agora.consensus.state.Ledger] - Transactions: 0 - Enrollments: 6
2022-01-19 14:34:23,305 Info [agora.consensus.state.Ledger] - Validators: Active: 20 - Signing: 11111111111111111111 - Slashed: 0
2022-01-19 14:34:23,306 Fatal [agora.consensus.state.Ledger] - Error while adding a new validator: This validator is already enrolled
2022-01-19 14:34:23,306 Fatal [agora.consensus.state.Ledger] - Enrollment #0: { utxo_key: 0x0666c4d505b55b6840fbb669ec08a1849e699d5a30ba246989b65ea71292f8ac9a3d7126ca9061313d3225d6e324146f37cdc5dab51facbbc3beead6854e89a4, commitment: 0xacc94967f8ad17f622c883c782cdcc01387e7e49d6c5cadaf3db6f4744895dfedefa115d15667bbc0904ec3f01358afbb6b05bf5980b2f47e59b2d9a01378062, enroll_sig: 0xf1d9d0a109830f568657023912709ff8e2bb2ca4b1e58ade48a52424e057e67607c05a89c14ef8e81b5800254f62249df7bfbf28881aeaedfa4db6ac1d141dfd }
```

**Comment by Geod24** [comment]
This seems to be working. The issue I had was because my config file didn't have the correct `ConsensusConfig`, although it should not have crashed.

**Review by hewison-chris — APPROVED** [review]
LGTM, although at some point it should probably support a subset of the validators in the GenesisBlock in makeConsensusParams.

**Pull request merged**
