### PR TITLE
Use TxBuilder directly again

### PR DESCRIPTION
**Pull request by hewison-chris**
The `Builder` `struct` was created with the intention of making it
easier to override the `unlocker` used in the signing of `transactions`.
This is now required as we are not always using the `well known keys`
from the source file but can provide keys in the config file.
However the `Builder` `struct` had a bug which meant that the `sign` was
not being called when intended.
This now uses an alternative way which still uses the TxBuilder `sign`
function but calls with a new `unlocker` delegate.

### CODE REVIEW

**Comment by Geod24** [comment]
I don't quite understand. What's the bug being fixed ? Why do we have to revert ? It doesn't seem like there's any functional change here ?

**Comment by hewison-chris** [comment]
> I don't quite understand. What's the bug being fixed ? Why do we have to revert ? It doesn't seem like there's any functional change here ?

When debugging it looked to me that the `Builder.sign` was not being called but the `TxBuilder.sign` in both the `splitTx` and `mergeTx`. As we just need to override the `unlocker delegate` in the `sign` I was trying a simpler approach to see if the signing then created valid `tx` signatures. The second commit addresses a different bug I found after making sure the correct `unlocker` was being used. However, I still need to check if this resolves the issue `Rejected tx. Reason: LockType.Key signature in unlock script failed validation.`

**Comment by Geod24** [comment]
> However the `Builder` `struct` had a bug which meant that the `sign` was not being called when intended.

It's not a bug though, more of an oversight in the API / usage. There's two ways forward:
- Revert to TxBuilder, which this does;
- Expose all functions in `Builder` so that we use the correct `this`;

I think going with the first one like you did is the most sensible. In which case the commit message, instead of the above vague "there is a bug" mention should be something along the lines of:
> However the `TxBuilder` API which allows chaining by returning a `ref` to `this` make this very error prone, as any chaining means the wrong `sign` will be called. Instead of overriding all methods and removing the `alias this`, it is more scalable to just ensure we call `sign` correctly.

**Comment by hewison-chris** [comment]
Unfortunately there is still a problem to be fixed with the signing when we are merging utxos. Will convert to draft PR until this is resolved.

**Comment by hewison-chris** [comment]
> Unfortunately there is still a problem to be fixed with the signing when we are merging utxos. Will convert to draft PR until this is resolved.

Ready for review. Will address any bugs in a new PR.

**Pull request merged**
